filename: app-test
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

alerter:
  telegram:
    chatId: -1234567890123
    token: 1234567890:THISISATESTATOKENABCDEFGHUJIKLMNOPQ