filename: app
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: local
    password: local

alerter:
  telegram:
    chatId: -1234567890123
    token: 1234567890:THISISATESTATOKENABCDEFGHUJIKLMNOPQ