filename: app
spring:

  application:
    name: common-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      trusted_packages: "m3.common.dto.rq, m3.lib.dto.rq, m3.game.dto.rq"
    topicName: 'topic-common'

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy

logging:
  level:
    root: info

alerter:
  telegram:
    chatId: ${TELEGRAM_CHAT_ID}
    token: ${TELEGRAM_TOKEN}

server:
  port: 8088